export const
  LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAIL = 'LOGIN_USER_FAIL',
  GET_USERS_SUCCESS = 'GET_GROUPS_SUCCESS',
  GET_USERS_FAIL = 'GET_GROUPS_FAIL',
  LOGOUT_USER = 'LOGOUT_USER'

